version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-config.json
      - KC_HOSTNAME=192.168.188.20
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY=edge
      - KC_CSP_FRAME_SRC="*"
      - QUARKUS_HTTP_HEADERS_CONTENT_SECURITY_POLICY="frame-src *; frame-ancestors *; object-src *;"
    ports:
      - "8080:8080"
      - "9001:9000"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    networks:
      keycloak_net:
        ipv4_address: 172.28.0.10

networks:
  keycloak_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16